
   services:
     

     backend:
       build: ./Backend
       container_name: backend
       ports:
         - "5000:5000"
       env_file:
         - ./Backend/.env

     compilerbackend:
       build: ./CompilerBackend
       container_name: compilerbackend
       ports:
         - "5001:5001"
       env_file:
         - ./CompilerBackend/.env

     frontend:
       build: ./Frontend
       container_name: frontend
       ports:
         - "5173:5173"
       env_file:
         - ./Frontend/.env

   volumes:
     mongo_data: