version: '3.8'

services:
  backend:
    image: 548982503885.dkr.ecr.ap-south-1.amazonaws.com/online-judge-backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://ABR_03:Abhyuday2005@cluster0.kwgww1e.mongodb.net/online_judge?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=Abhyuday200520090301
      - GEMINI_API_KEY=YOUR_REAL_GEMINI_API_KEY_HERE
    restart: unless-stopped

  compilerbackend:
    image: 548982503885.dkr.ecr.ap-south-1.amazonaws.com/online-judge-compiler:latest
    container_name: compilerbackend
    ports:
      - "8000:5001"
    environment:
      - PORT=5001
    restart: unless-stopped

  frontend:
    image: 548982503885.dkr.ecr.ap-south-1.amazonaws.com/online-judge-frontend:latest
    container_name: frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://13.232.96.186:5000/api
    restart: unless-stopped

volumes:
  mongo_data: 